# Site settings
title: yoshdog 
header-img: img/home-bg.jpg
email: toan@graduate.uwa.edu.au 
description: "Walking the long road towards mastery"
baseurl: ""
url: "https://yoshdog.github.io"
twitter_username: ToanJuan
github_username:  yoshdog
facebook_username: yoshdog07 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems:
  - octopress-solarized
